#!/bin/bash

CMD="npm test"
protected_branch='master'

# Check if there are commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
    exit 0
fi

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ $current_branch = $protected_branch ]]; then
    $CMD
    RESULT=$?
    if [ $RESULT -ne 0 ]; then
        echo "FAILED :: $CMD"
        exit 1
    fi
fi

exit 0
